replicaCount: 1

image:
  repository: viresh1994/my-maven-app
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 8080
  nodePort: 30080

imagePullSecrets:
  - name: dockerhub-secret
