apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-maven-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-maven-app
  template:
    metadata:
      labels:
        app: my-maven-app
    spec:
      containers:
      - name: my-maven-app
        image: <DOCKERHUB_USERNAME>/my-maven-app:latest
      imagePullSecrets:
      - name: dockerhub-secret
        ports:
        - containerPort: 8080
