---
apiVersion: v1
kind: Service
metadata:
  name: my-maven-app-service
spec:
  type: NodePort
  selector:
    app: my-maven-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
