# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:

  workflow_dispatch:
  # push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

jobs:
  build:

    runs-on: [self-hosted, Linux]
    #runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-maven-app:latest .

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-maven-app:latest

    - name: Verify Docker image
      run: docker images
      
  deploy:
    # Use your self-hosted runner (Windows VM with Minikube)
    runs-on: Linux
    environment:
      name: staging 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Verify Helm
      run: helm version

    - name: Clean old resources (optional)
      run: |
        kubectl delete deployment my-maven-app || true
        kubectl delete svc my-maven-app-service || true

    - name: Deploy using Helm
      run: |
          helm upgrade --install my-maven-app ./my-maven-app \
            --set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/my-maven-app \
            --set image.tag=latest \
            --set image.pullPolicy=Always \
            --set service.type=NodePort \
            --set service.port=8080 \
            --set service.nodePort=30080
    - name: Verify Deployment
      run: |
          kubectl rollout status deployment/my-maven-app --timeout=60s
          kubectl get pods -o wide
          kubectl get svc my-maven-app-service
    
    # - name: Deploy to Minikube
    #   run: |
    #     kubectl delete deployment my-maven-app --force --grace-period=0
    #     kubectl apply -f k8s/deployment.yaml
    #     kubectl apply -f k8s/service.yaml
    #     kubectl rollout status deployment/my-maven-app --timeout=60s
